### ISSUE TITLE
Picker goes back a few values when pressing Done

### ISSUE THREAD

**Issue by dragonfire1119** [lawnstarter/react-native-picker-select#209] opened 2019-08-08 15:45 UTC
**Describe the bug**<br />
When I tried ^6.0.0 & went from 5.2.5 I started getting reports that on iPad's it went back a few values when pressing Done. If they don't press Done & just dismiss the value stay's correctly.

**To Reproduce**<br />

1.  Go to to the picker with a few values or so
2.  Click on the picker
3.  Scroll down to value & press Done
4.  You should now see that it isn't on the value that you want

**Expected behavior**<br />
When you press done it should stay on the value that you selected.

**Screenshots**<br />
n/a

**Additional details**<br />
-   Device: iPad
-   OS: iOS
-   react-native-picker-select version: 6.0.0+
-   react-native version: 0.60.3
-   react version: 16.8.6

**Reproduction and/or code sample**<br />
It's honestly really hard to reproduce but it seems to only happen on iPad's. I know that when I revert to 5.2.5 from ^6.0.0 it started working for pressing the Done button. So right now the only solution for a quick fix is to set ``"react-native-picker-select": "5.2.5"`` in package.json.

**Comment by lfkwtz** [comment] 2019-08-08 16:20
Weird - nothing obvious I can see causing this has changed since 5.2.5 - but I rarely test this on an iPad so anything is possible. Will try to reproduce when I get a moment.

**Comment by dragonfire1119** [comment] 2019-08-10 16:45
@lfkwtz I know it's weird. I've compared the version tags & don't see much that could make it happen but I haven't had a lot of time to look into it more though. It's something between those versions though because the Done button does start working with 5.2.5. Thanks for your time & this awesome project!

**Comment by awinograd** [comment] 2019-08-15 17:27
I'm noticing this issue to on 6.3.0

Tried to debug for a while before I found this issue. When done is pressed, the native `Picker` component seems to be calling `onValueChange` again which seems bizarre to me. Hope that's helpful. I'll post back if I learn more

**Comment by awinograd** [comment] 2019-08-15 17:53
^ Fix is in the linked PR. Looks like a necessary zIndex got removed from styles. Perhaps it's not needed on android

**Closed** 2019-08-15 18:00 UTC
Labels: help wanted

**Comment by fattomhk** [comment] 2019-08-30 09:19
@awinograd 
I installed the latest version and the done button cannot be clicked.
```
<RNPickerSelect
						ref={ref => {
							this.select = ref;
						}}
						disabled={false}
						placeholder={{}}
						useNativeAndroidPickerStyle={false}
						value={this.props.screenProps.locale}
						items={[{ label: '繁體中文', value: 'zh-hk' }, { label: '简体中文', value: 'zh-cn' }]}
						doneText={i18n.t('Buttons.OK')}
						onDonePress={() => {
							console.warn('Checkpoint');
						}}
						onValueChange={value => {
							if (!value || value === this.props.screenProps.locale) return;
							this.props.screenProps.setLocale(value);
							this.updateData(value);
						}}
					/>
```
