### ISSUE TITLE
Tried to register two views with the same name AndroidDropdownPicker

### ISSUE THREAD

**Issue by appukuttan-shailesh** [lawnstarter/react-native-picker-select#320] opened 2020-05-03 22:27 UTC
**Describe the bug**<br />
Getting error with following message:
> Tried to register two views with the same name AndroidDropdownPicker

The error seems to be similar to this:
https://github.com/react-native-community/react-native-picker/issues/15

**To Reproduce**<br />
In my project, I have used also this component:
import { Picker } from '@react-native-community/picker';
I believe it is a clash between these components. Any way to avoid this error and be able to use both?

**Expected behavior**<br />
Be able to use this component without clashing with other components.

**Screenshots**<br />
 "n/a".

**Additional details**<br />
-   Device: Android
-   OS: Android 10
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.62.2
-   react version: 16.11.0

**Reproduction and/or code sample**<br />
```
import React, { useState } from 'react';
import { StyleSheet, TouchableNativeFeedback, View, Text, Image } from 'react-native';
import RNPickerSelect from 'react-native-picker-select';

export default function AdminHome({ navigation }) {
    return (
            <View>
                <RNPickerSelect
                accessibilityLabel={'gender'}
                    onValueChange={(value) => console.log(value)}
                    items={[
                        { label: 'Football', value: 'football' },
                        { label: 'Baseball', value: 'baseball' },
                        { label: 'Hockey', value: 'hockey' },
                    ]}
                />
        </View>
    );
}
```

**Comment by appukuttan-shailesh** [comment] 2020-05-03 22:33
Also, the solution mentioned [here](https://github.com/react-native-community/react-native-picker/issues/15#issuecomment-567101445) did not work for me. All my imports of that component already were:
`import { Picker } from '@react-native-community/picker';`

**Comment by badarshahzad** [comment] 2020-05-19 07:54
+1

I have also faced the same issue
![Screenshot from 2020-05-19 12-45-33](https://user-images.githubusercontent.com/19945367/82300119-d770df00-99cf-11ea-8926-36fe9c3e8fa1.png)

**Comment by badarshahzad** [comment] 2020-05-19 08:03
> +1
> 
> I have also faced the same issue
> ![Screenshot from 2020-05-19 12-45-33](https://user-images.githubusercontent.com/19945367/82300119-d770df00-99cf-11ea-8926-36fe9c3e8fa1.png)

These are the libraries version im using
`"@react-native-community/picker": "^1.5.0",`
`"react": "16.9.0",`
`"react-native": "0.61.2",`

**Comment by lfkwtz** [comment] 2020-05-21 21:02
sounds like the issue is using both this library and the newly abstracted Picker library.

either that library will need to be updated to handle this scenario - or this'll be solved once #303 is merged in.

**Comment by androxxe** [comment] 2020-06-03 19:30
i have the same issue

**Comment by n3rd253** [comment] 2020-07-19 08:51
Any idea when this will be merged?

**Closed** 2020-08-04 14:05 UTC
Labels: duplicate

**Comment by plgrazon** [comment] 2020-10-07 20:19
I know this has been closed. 8.0.1 Fixed my iOS issues but it started breaking my Android build.

**Comment by lfkwtz** [comment] 2020-10-07 20:51
@plgrazon worth opening a new report

**Comment by RajatKumarChahar** [comment] 2020-10-08 04:28
Build is failing for android

**Comment by plgrazon** [comment] 2020-10-08 13:50
> @plgrazon worth opening a new report

Yup! Just did issue #374

**Comment by higor21** [comment] 2020-12-07 23:41
I fixed this problema installing the following versions:
`"@react-native-community/picker": "1.6.0",
    "react-native-picker-select": "7",`

**Comment by whatdtech** [comment] 2020-12-15 09:16
`@react-native-community/picker` deprecated. So remove it by `yarn remove @react-native-community/picker` and install `@react-native-picker/picker` . this solved the issue for me.

**Comment by nayookyaw** [comment] 2021-03-03 10:01
I changed react-native-community/datetimepicker version from

2.4.0 to 3.0.9

"@react-native-community/datetimepicker": "^3.0.9"

We can assume the old version will get error
