### ISSUE TITLE
Icon prop type error

### ISSUE THREAD

**Issue by simvi** [lawnstarter/react-native-picker-select#499] opened 2023-02-08 09:58 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-picker-select@8.0.4` for the project I'm working on.

The type of Icon was invalid for Icon prop.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-picker-select/index.d.ts b/node_modules/react-native-picker-select/index.d.ts
index 9f111bc..09644ca 100644
--- a/node_modules/react-native-picker-select/index.d.ts
+++ b/node_modules/react-native-picker-select/index.d.ts
@@ -83,7 +83,7 @@ export interface PickerSelectProps {
     pickerProps?: CustomPickerProps;
     touchableDoneProps?: CustomTouchableDoneProps;
     touchableWrapperProps?: CustomTouchableWrapperProps;
-    Icon?: React.ReactNode;
+    Icon?: React.FC;
     InputAccessoryView?: React.ReactNode;
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tdraper-dev** [comment] 2023-03-09 17:22
Do you recall if running `patch-package` for this library was an incredibly slow operation? I'm currently trying to run a patch on it myself and it _seems_ like it's hanging.

**Comment by hrdyjan1** [comment] 2023-07-17 13:02
> @simvi Do you recall if running `patch-package` for this library was an incredibly slow operation? I'm currently trying to run a patch on it myself and it _seems_ like it's hanging.

We were also struggling with `npm`, using `yarn `solved the problem.

**Comment by devinMcArthur** [comment] 2023-08-30 19:48
To anyone interested, [this](https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L395) is why `Icon` must be a `React.FC`, it is being called like a component here, not a `ReactNode`. 

If `Icon` was truly meant to be a `ReactNode`, `renderIcon` would look like this:
```
renderIcon() {
    const { style, Icon } = this.props;

    if (!Icon) {
        return null;
    }

    return (
        <View
            testID="icon_container"
            style={[defaultStyles.iconContainer, style.iconContainer]}
        >
            {Icon}
        </View>
    );
}
```

**Comment by lfkwtz** [comment] 2023-11-27 15:42
anyone want to open a pr for this?

**Comment by lfkwtz** [comment] 2023-11-27 15:45
dupe of #478

**Closed by lfkwtz** 2023-11-27 15:45 UTC
