### ISSUE TITLE
RNPickerSelect as render item of Flatlist, not able to select picker item.

### ISSUE THREAD

**Issue by maniyarpayal** [lawnstarter/react-native-picker-select#111] opened 2018-11-15 06:14 UTC
**Describe the bug**
Use **RNPickerSelect** as renderItem of Flatlist, we can not select any picker value. Once we scroll the picker to select value, it automatically scrolls to top.It works perfectly fine when it is not used as renderItem of Flatlist.

**Expected behavior**
As renderitem of Flatlist, it should allow to select picker value.

**Screenshots**

![bug](https://user-images.githubusercontent.com/18752134/48533752-af308d80-e8cb-11e8-932d-14380446f8a8.gif)

**Smartphone (please complete the following information):**

-   Device: simulator
-   OS: iOS
-   react-native-picker-select version:^5.0.0
-   react-native version: 0.57.1

**Comment by maniyarpayal** [comment] 2018-11-15 11:35
@lfkwtz please check above issue....

**Comment by lfkwtz** [comment] 2018-11-15 15:03
Please provide a link to a reproduction of this issue on https://snack.expo.io and/or a code sample showing your implementation of the library

**Comment by lfkwtz** [comment] 2018-11-28 12:12
@maniyarpayal

**Comment by grissproject** [comment] 2018-12-02 06:00
I've faced the same issue when I assigned an object `{ label:  'orange', value: 'orange' }` to the value prop, I worked for me when I assigned a string instead. I think this is related to https://github.com/lawnstarter/react-native-picker-select/issues/45.

**Comment by lfkwtz** [comment] 2018-12-09 13:11
@grissproject was your implementation also part of a flat list?

**Comment by lfkwtz** [comment] 2018-12-09 13:15
@maniyarpayal not able to reproduce (https://snack.expo.io/B1KrrqckN) works fine here.

going to close this out -- @grissproject please open a new issue if you can reproduce the bug you mentioned. thank you.

**Closed by lfkwtz** 2018-12-09 13:15 UTC

**Comment by wei0265** [comment] 2021-03-24 03:37
i have same problem with FlatList
